name: "ILEO Scraper"
version: "1.14" # role manager sur hass.io
slug: "ileo_scraper"
description: "Scraper de consommation d'eau ILEO avec envoi MQTT"
url: "https://github.com/hal01/ILEO_HA_Scraper_AddOn"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: application
init: false
hassio_api: true
hassio_role: manager

# Note : build_from est souvent géré directement dans le Dockerfile
# Si vous avez un Dockerfile, vous pouvez supprimer ces lignes build_from ci-dessous
build_from:
  aarch64: "ghcr.io/home-assistant/base-python:3.11"
  amd64: "ghcr.io/home-assistant/base-python:3.11"
  armv7: "ghcr.io/home-assistant/base-python:3.11"
  armhf: "ghcr.io/home-assistant/base-python:3.11"

options:
  ileo_username: ""
  ileo_password: ""
  mqtt_topic: "ileo/consommation"
  frequency: 240

schema:
  ileo_username: str
  ileo_password: str
  mqtt_topic: str
  frequency: int

map:
  - config
  - ssl
  - share
